name: Update Submodules

on:
  schedule: 
    - cron: 0 0 * * *

  workflow_dispatch:

jobs:
  sync:
    name: Update Submodules
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Update submodules
      shell: bash
      run: |
        git submodule update --init --recursive
        git submodule update --remote --merge

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update submodules
